### ISSUE TITLE
Run this project and get vulkan validation error.

### ISSUE THREAD

**Issue by yuxiao-ash** [Supercip971/compute-ray#1]
Hi, thanks for your project !
I make this project on my computer with vulkan sdk 1.3.239.0 and get a vulkan validation error as below, do you know how to slove this problem?

[VULKAN] [1;32minfo: [1;36mvalidation: [0mValidation Information: [ UNASSIGNED-cache-file-error ] Object 0: handle = 0x55f97a1dc760, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf0bb3995 | Cannot open shader validation cache at /root/.cache/shader_validation_cache-0.bin for reading (it may not exist yet)
55f97a0d4280 dev fab64d0000000002 surface 
mode[0]: 0
mode[1]: 1
mode[2]: 2
mode[3]: 3
candidate[0]: 2048
  / 2048
 candidate[1]: 2048
  / 2048
 candidate[2]: 2048
  / 2048
 candidate[3]: 2048
  / 2048
 textures sizes: 67108864  
[VULKAN] [1;31m**error**: [1;36mvalidation: [0mValidation Error: [ VUID-VkWriteDescriptorSet-descriptorType-02997 ] Object 0: handle = 0x2e2cd000000002b, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x40eb75ef | VkWriteDescriptorSet: image view must not be VK_NULL_HANDLE. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, or VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, and the nullDescriptor feature is not enabled, the imageView member of each element of pImageInfo must not be VK_NULL_HANDLE (https://vulkan.lunarg.com/doc/view/1.3.239.0/linux/1.3-extensions/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-02997)
[VULKAN] [1;31m**error**: [1;36mvalidation: [0mValidation Error: [ VUID-VkWriteDescriptorSet-descriptorType-00325 ] Object 0: handle = 0x2e2cd000000002b, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xce76343a | vkUpdateDescriptorSets() pDescriptorWrites[0] failed write update validation for VkDescriptorSet 0x2e2cd000000002b[] with error: Write update to VkDescriptorSet 0x2e2cd000000002b[] allocated with VkDescriptorSetLayout 0xba7514000000002a[] binding #7 failed with error message: Attempted write update to sampler descriptor with invalid sampler: VkSampler 0x0[].. The Vulkan spec states: If desc

**Comment by Supercip971** [comment]
Hi ! Are you using a 3D model that doesn't have any texture ?

**Comment by Supercip971** [comment]
Hi ! 
The issue was that I haven't included the skymap in the GitHub. But I should handle the case where the skymap can't be found. The program should also be able to be provided with a specific skymap instead of just being hard-coded. So I don't mark this issue as "fixed".
But, thank you very much !

**Comment by yuxiao-ash** [comment]
> Hi ! The issue was that I haven't included the skymap in the GitHub. But I should handle the case where the skymap can't be found. The program should also be able to be provided with a specific skymap instead of just being hard-coded. So I don't mark this issue as "fixed". But, thank you very much !

Thanks，it did help me! After I add a skymap png and delete those two ray tracing EXT in comp.comp, I run this project successfully!
Two more question,
1) the camera move a long distance when I touch my mouse just a little. So it is hard for me to adjust the camera toward the model scene.
2) the terminal print info is always "a1 1xx.xxxxxx 0", is that "0" means no ray accumulated to decrease noise?

**Comment by Supercip971** [comment]
1. There is a way to control the camera position speed by using the scroll wheel. But I should also use it when you change camera orientation.
2. Yes It means that the camera moved so it restarted the ray accumulation. If you want you can also disable camera controls in the config.h file. 
+ Thanks for your interest in the project !

**Comment by yuxiao-ash** [comment]
> 

Got it. But I cannot see my model at the initial camera setting, so it is useless to disable camera controls.
